### ISSUE TITLE
error msg

### ISSUE THREAD

**Issue by hdstar2009** [RoyalAliceAcademyOfSciences/CnRexmit#3]
got an error meg like this :GeoIP_db_avail Error.

**Comment by AuroraRAS** [comment]
请告诉我您的平台是Linux还是Windows？

Please tell me your platform is Linux or Windows?

**Comment by hdstar2009** [comment]
linux的。openvz平台。

**Comment by AuroraRAS** [comment]
推测缺少GeoIP.dat文件，但不清楚该文件在您的发行版下应处于什么目录

尝试按照您的Linux发行版所提供文档重新安装libgeoip

**Comment by hdstar2009** [comment]
root@webserver:~# apt-get install libgeoip-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libgeoip-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.

libgeoip有装，但是你说的GeoIP.dat文件find / -name GeoIP.dat  没有找到。

在 2015年3月19日 上午7:17，MiniLight notifications@github.com写道：

**Comment by hdstar2009** [comment]
GeoIP.dat
我大概百度了下，这个文件似乎不是libgeoip自带的，很多人都是网络下载，你这个文件放到什么目录上被调用？或者直接放个你用的文件到github是试下？

2015-03-19 8:38 GMT+08:00 Itsme_ up hdstar2009@gmail.com:

**Comment by AuroraRAS** [comment]
我不是很清楚它应该被放在什么地方，每个发行版都是不一样的，你要根据自己的发行版具体搜索
